"""Badge generation tests: valid SVG, correct counts, data-URI markdown."""
from __future__ import annotations

import base64

from prsnoop.badge import (
    BADGES,
    render_badge,
    render_badge_merge_rate,
    render_badge_merged,
    render_badge_prs,
    render_badge_streak,
)


class TestSVG:
    def test_prs_badge_shape(self, activity):
        svg = render_badge_prs(activity)
        assert svg.startswith("<svg")
        assert svg.endswith("</svg>")
        assert "prsnooped PRs" in svg
        assert ">3<" in svg  # 3 PRs in the fixture

    def test_merged_badge_green(self, activity):
        svg = render_badge_merged(activity)
        assert "2ea043" in svg  # GitHub merged green
        assert ">2<" in svg

    def test_merge_rate_amber(self, activity):
        svg = render_badge_merge_rate(activity)
        assert "d29922" in svg  # GitHub amber
        assert "67%" in svg

    def test_streak_badge(self, activity):
        svg = render_badge_streak(activity)
        assert "longest streak" in svg
        assert "d" in svg

    def test_all_badges_ascii(self, activity):
        for fn in BADGES.values():
            fn(activity).encode("ascii")

    def test_empty_activity(self, now):
        from prsnoop.stats import build_activity

        empty = build_activity("nobody", [], [], [], now=now)
        svg = render_badge_prs(empty)
        assert ">0<" in svg


class TestMarkdown:
    def test_render_badge_block(self, activity):
        out = render_badge(activity)
        assert out.startswith("<!-- Generated by prsnoop")
        assert "data:image/svg+xml;base64," in out
        assert out.count("![") == 4

    def test_data_uris_decode_to_valid_svg(self, activity):
        out = render_badge(activity)
        for line in out.splitlines():
            if line.startswith("!["):
                payload = line.split("base64,")[1].rstrip(")")
                svg = base64.b64decode(payload).decode("ascii")
                assert svg.startswith("<svg")
