"""Tests for 1.6: card, radar, changelog, ci gates, watch, replay."""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone

import pytest

from prsnoop import cli
from prsnoop.card import render_card
from prsnoop.changelog import (
    build_changelog,
    categorize,
    render_changelog_json,
    render_changelog_markdown,
)
from prsnoop.ci import check_gates, render_summary
from prsnoop.models import Activity, PRRecord
from prsnoop.radar import (
    bucket_for,
    fetch_radar,
    render_radar_csv,
    render_radar_markdown,
    render_radar_table,
)
from prsnoop.stats import build_activity
from prsnoop.watch import diff_keys, pr_keys, render_frame
from prsnoop.wrapped import build_wrapped, render_wrapped_table


def _pr(
    days_ago: float,
    repo: str = "acme/app",
    merged: bool = True,
    adds: int = 150,
    comments: int = 0,
    number: int = 1,
    title: str = "add thing",
) -> PRRecord:
    created = datetime.now(timezone.utc) - timedelta(days=days_ago)
    merged_at = created + timedelta(days=0.5) if merged else None
    return PRRecord(
        repo=repo,
        number=number,
        title=title,
        url=f"https://github.com/{repo}/pull/{number}",
        state="merged" if merged else "open",
        created_at=created,
        merged_at=merged_at,
        additions=adds,
        deletions=adds // 3,
        changed_files=2,
        comments=comments,
    )


# ---------------------------------------------------------------- replay


def test_activity_round_trip_preserves_everything():
    prs = [_pr(1), _pr(3, merged=False, adds=40)]
    act = build_activity("t", prs, [], [], window_days=30)
    restored = Activity.from_dict(act.to_dict())
    assert restored.user == "t"
    assert len(restored.prs) == 2
    assert restored.prs[0].state == "merged"
    assert restored.prs[0].merged_at is not None
    assert restored.stats.prs_authored == 2
    assert restored.stats.top_repos == act.stats.top_repos
    assert restored.stats.day_activity == act.stats.day_activity
    # second round trip is stable
    assert restored.to_dict() == act.to_dict()


def test_activity_round_trip_with_trend():
    from prsnoop.stats import TrendDelta, build_trend

    prs = [_pr(1), _pr(2)]
    act = build_activity("t", prs, [], [], window_days=30)
    prev = build_activity("t", [_pr(20)], [], [], window_days=30)
    act.trend = build_trend(act.stats, prev.stats)
    restored = Activity.from_dict(act.to_dict())
    assert len(restored.trend) == len(act.trend)
    first = restored.trend[0]
    assert isinstance(first, TrendDelta)
    assert first.key == act.trend[0].key
    assert first.current == act.trend[0].current


def test_activity_round_trip_rejects_garbage():
    with pytest.raises((KeyError, TypeError, ValueError)):
        Activity.from_dict({"nope": True})


def test_replay_command_renders_offline(tmp_path, capsys):
    prs = [_pr(1), _pr(4, merged=False, adds=30)]
    act = build_activity("t", prs, [], [], window_days=30)
    snap = tmp_path / "snap.json"
    snap.write_text(json.dumps(act.to_dict()), encoding="utf-8")
    rc = cli.run(["replay", str(snap)])
    assert rc == 0
    out = capsys.readouterr().out
    assert "prsnoop | t" in out
    # json replay goes through the same snapshot
    rc = cli.run(["replay", str(snap), "-f", "json"])
    assert rc == 0
    payload = json.loads(capsys.readouterr().out)
    assert payload["stats"]["prs_authored"] == 2


def test_replay_wrapped_from_snapshot(tmp_path, capsys):
    prs = [_pr(1)]
    act = build_activity("t", prs, [], [], window_days=30)
    snap = tmp_path / "snap.json"
    snap.write_text(json.dumps(act.to_dict()), encoding="utf-8")
    rc = cli.run(["replay", str(snap), "--wrapped"])
    assert rc == 0
    assert "THE YEAR IN PULL REQUESTS" in capsys.readouterr().out


def test_replay_rejects_bad_files(tmp_path, capsys):
    bad = tmp_path / "bad.json"
    bad.write_text("not json", encoding="utf-8")
    assert cli.run(["replay", str(bad)]) == 2
    wrong = tmp_path / "wrong.json"
    wrong.write_text(json.dumps([1, 2]), encoding="utf-8")
    assert cli.run(["replay", str(wrong)]) == 2
    missing = tmp_path / "missing.json"
    assert cli.run(["replay", str(missing)]) == 2


# ---------------------------------------------------------------- card


def test_card_renders_svg_scoreboard():
    prs = [_pr(1), _pr(2), _pr(3, merged=False, adds=30)]
    act = build_activity("simonw", prs, [], [], window_days=30)
    svg = render_card(act)
    assert svg.startswith("<svg")
    assert "simonw" in svg
    assert "Merge rate" in svg.upper() or "merge rate" in svg.lower()
    assert "generated by prsnoop" in svg
    # sparkline drawn for a window with activity
    assert "<polyline" in svg


def test_card_theme_variants():
    prs = [_pr(1)]
    act = build_activity("t", prs, [], [], window_days=30)
    dark = render_card(act, theme="dark")
    light = render_card(act, theme="light")
    assert "#0d1117" in dark
    assert "#ffffff" in light
    unknown = render_card(act, theme="nope")
    assert "#0d1117" in unknown  # falls back to dark


def test_card_escapes_xml_entities():
    prs = [_pr(1, title="fix <tag> & 'stuff'")]
    act = build_activity("t", prs, [], [], window_days=30)
    svg = render_card(act)
    # the card is well-formed XML even when PR titles are not SVG-safe
    import xml.etree.ElementTree as ET

    ET.fromstring(svg)  # raises on malformed markup


# ---------------------------------------------------------------- radar


def test_bucket_boundaries():
    assert bucket_for(0) == "fresh"
    assert bucket_for(2) == "fresh"
    assert bucket_for(3) == "aging"
    assert bucket_for(13) == "aging"
    assert bucket_for(14) == "stale"
    assert bucket_for(29) == "stale"
    assert bucket_for(30) == "ancient"


class _RadarFake:
    def __init__(self, items: list[dict]) -> None:
        self.items = items

    def paginate(self, path: str, params: dict | None = None) -> list[dict]:
        assert path.startswith("/repos/")
        return self.items


def _open_item(number: int, age_days: int, author: str = "dev") -> dict:
    created = datetime.now(timezone.utc) - timedelta(days=age_days)
    return {
        "number": number,
        "title": f"pr {number}",
        "html_url": f"https://github.com/acme/app/pull/{number}",
        "state": "open",
        "created_at": created.isoformat().replace("+00:00", "Z"),
        "updated_at": created.isoformat().replace("+00:00", "Z"),
        "user": {"login": author},
        "draft": False,
        "labels": [],
        "comments": 0,
    }


def test_fetch_radar_ages_and_buckets():
    items = [
        _open_item(1, 1),
        _open_item(2, 20),
        _open_item(3, 45),
        _open_item(4, 8),
    ]
    report = fetch_radar(_RadarFake(items), "acme/app")
    assert report.total_open == 4
    buckets = report.buckets
    assert buckets["fresh"] == 1 and buckets["stale"] == 1
    assert buckets["ancient"] == 1 and buckets["aging"] == 1
    assert report.entries[0].age_days == 45  # oldest first
    assert report.median_age_days == 14.0
    assert report.entries[0].is_quiet


def test_radar_renders():
    items = [_open_item(7, 33, author="sam"), _open_item(2, 1)]
    report = fetch_radar(_RadarFake(items), "acme/app")
    table = render_radar_table(report)
    assert "prsnoop radar | acme/app" in table
    assert "ancient" in table and "sam" in table
    md = render_radar_markdown(report)
    assert "# Radar: acme/app" in md
    assert "[#7]" in md
    csv_out = render_radar_csv(report)
    lines = csv_out.strip().splitlines()
    assert lines[0].startswith("number,age_days")
    assert "7,33,ancient,sam" in lines[1]


def test_radar_empty_queue():
    report = fetch_radar(_RadarFake([]), "acme/app")
    assert "queue is clear" in render_radar_table(report)
    assert "no open pull requests" in render_radar_markdown(report)


def test_radar_draft_and_truncation():
    item = _open_item(9, 40)
    item["draft"] = True
    report = fetch_radar(_RadarFake([item]), "acme/app", limit=1)
    assert report.entries[0].draft is True
    big = [_open_item(i, i % 40) for i in range(1, 6)]
    report = fetch_radar(_RadarFake(big), "acme/app", limit=3)
    assert report.total_open == 3
    assert report.truncated is True
    assert "capped at 40" in render_radar_table(report)


def test_radar_cli_rejects_bad_repo(capsys):
    assert cli.run(["radar", "norepo"]) == 2


# ---------------------------------------------------------------- changelog


def test_categorize_rules():
    assert categorize("feat: add x", []) == "Added"
    assert categorize("fix: crash", []) == "Fixed"
    assert categorize("Add a thing", ["enhancement"]) == "Added"
    assert categorize("bump requests to 2.0", []) == "Dependencies"
    assert categorize("docs: rewrite guide", []) == "Documentation"
    assert categorize("perf: faster loop", []) == "Performance"
    assert categorize("refactor: tidy", []) == "Changed"
    assert categorize("test: cover edge", []) == "Tests"
    assert categorize("drop python 3.9", ["breaking"]) == "Breaking changes"
    assert categorize("misc", []) == "Other"


class _ChangelogFake:
    def __init__(self, items: list[dict], tag_date: dict | None = None) -> None:
        self.items = items
        self.tag_date = tag_date

    def paginate(self, path: str, params: dict | None = None) -> list[dict]:
        assert path == "/search/issues"
        return self.items

    def get(self, path: str) -> dict:
        return self.tag_date or {}


def _merged_item(number: int, title: str, author: str) -> dict:
    return {
        "number": number,
        "title": title,
        "html_url": f"https://github.com/acme/app/pull/{number}",
        "user": {"login": author},
        "labels": [],
        "pull_request": {"merged_at": "2026-08-20T10:00:00Z"},
    }


def test_build_changelog_groups_and_sorts():
    items = [
        _merged_item(1, "feat: first", "alice"),
        _merged_item(2, "fix: second", "bob"),
        _merged_item(3, "feat: third", "alice"),
    ]
    ch = build_changelog(_ChangelogFake(items), "acme/app", days=30)
    cats = ch.categories
    assert len(cats["Added"]) == 2 and len(cats["Fixed"]) == 1
    assert ch.contributors == ["alice", "bob"]
    md = render_changelog_markdown(ch)
    assert "### Added" in md and "### Fixed" in md
    assert "[#1](https://github.com/acme/app/pull/1)" in md
    assert "**3** merged pull requests from **2** contributors" in md


def test_changelog_json_roundtrip():
    items = [_merged_item(1, "feat: x", "alice")]
    ch = build_changelog(_ChangelogFake(items), "acme/app", days=7)
    payload = json.loads(render_changelog_json(ch))
    assert payload["repo"] == "acme/app"
    assert payload["entries"][0]["category"] == "Added"


def test_changelog_tag_resolution():
    class _TagFake:
        def get(self, path: str) -> dict:
            if "ref/tags" in path:
                return {"object": {"sha": "abc", "type": "commit"}}
            if "/commits/" in path:
                return {"commit": {"committer": {"date": "2026-08-01T00:00:00Z"}}}
            return {}

        def paginate(self, path: str, params: dict | None = None) -> list[dict]:
            return []

    since = build_changelog(_TagFake(), "acme/app", days=30, tag="v1.0.0").since
    assert since == "2026-08-01"


def test_changelog_bad_tag_falls_back_to_days():
    class _BadTagFake:
        def get(self, path: str) -> dict:
            raise RuntimeError("no network")

        def paginate(self, path: str, params: dict | None = None) -> list[dict]:
            return []

    ch = build_changelog(_BadTagFake(), "acme/app", days=14, tag="ghost")
    assert ch.since  # still produced a window from --days


def test_changelog_cli_rejects_bad_repo(capsys):
    assert cli.run(["changelog", "norepo"]) == 2


# ---------------------------------------------------------------- ci gates


def _stats_from(prs: list[PRRecord], reviews: int = 0):
    act = build_activity("t", prs, [], [], window_days=30)
    return act.stats


def test_check_gates_pass_and_fail():
    s = _stats_from([_pr(1), _pr(2)])
    gates = check_gates(s, min_prs=1, min_merged=1, min_merge_rate=50)
    assert all(g.passed for g in gates)
    gates = check_gates(s, min_prs=5, min_reviews=3)
    failed = [g for g in gates if not g.passed]
    assert len(failed) == 2
    assert failed[0].target == ">= 5"


def test_check_gates_merge_rate_and_latency():
    s = _stats_from([_pr(1), _pr(2), _pr(3, merged=False)])
    gates = check_gates(s, min_merge_rate=99)
    assert not gates[0].passed
    assert gates[0].actual == "67%"
    gates = check_gates(s, max_merge_days=10)
    assert gates[0].passed
    assert gates[0].actual.endswith("d")
    # no merges at all fails the latency gate honestly
    empty = _stats_from([_pr(2, merged=False)])
    gates = check_gates(empty, max_merge_days=1)
    assert gates[0].passed is False
    assert gates[0].actual == "no merges"


def test_ci_summary_markdown():
    prs = [_pr(1), _pr(2), _pr(3, merged=False)]
    act = build_activity("t", prs, [], [], window_days=30)
    gates = check_gates(act.stats, min_prs=5, min_merged=1)
    md = render_summary(act, gates)
    assert "## prsnoop: t" in md
    assert "1 of 2 gates failed" in md
    assert "### Gates" in md
    assert ":white_check_mark: pass" in md and ":x: fail" in md
    # report-only mode when no gates are configured
    assert "no gates configured" in render_summary(act, [])


def test_ci_cli_exit_codes(monkeypatch, capsys, tmp_path):
    def fake_fetch(
        client, user, days=30, include_reviews=True, org=None, since=None, until=None
    ):
        return [_pr(1)], [], [], True

    monkeypatch.setattr(cli, "fetch_user_activity", fake_fetch)
    monkeypatch.setattr(cli, "GitHubClient", lambda **kw: object())
    rc = cli.run(["ci", "t", "--min-prs", "5"])
    assert rc == 1
    rc = cli.run(["ci", "t", "--min-prs", "1"])
    assert rc == 0
    # step summary is appended when the env var points somewhere
    summary_path = tmp_path / "summary.md"
    summary_path.write_text("", encoding="utf-8")
    monkeypatch.setenv("GITHUB_STEP_SUMMARY", str(summary_path))
    cli.run(["ci", "t", "--min-prs", "1"])
    assert "prsnoop: t" in summary_path.read_text(encoding="utf-8")


# ---------------------------------------------------------------- watch


def test_pr_key_diffing():
    prs_a = [_pr(1, number=1), _pr(2, number=2, merged=False)]
    act_a = build_activity("t", prs_a, [], [], window_days=30)
    prs_b = prs_a + [_pr(3, number=3, merged=False)]
    act_b = build_activity("t", prs_b, [], [], window_days=30)
    assert pr_keys(act_a) == {"acme/app#1", "acme/app#2"}
    new, gone = diff_keys(pr_keys(act_a), pr_keys(act_b))
    assert new == {"acme/app#3"} and not gone
    # first tick reports nothing as new
    assert diff_keys(None, pr_keys(act_b)) == (set(), set())


def test_watch_frame_plain_and_ansi():
    from prsnoop.watch import CLEAR

    prs = [_pr(1), _pr(2, merged=False, number=2)]
    act = build_activity("t", prs, [], [], window_days=30)
    plain = render_frame(act, color=False)
    assert "prsnoop watch | t" in plain
    assert "last 30 days" in plain
    assert "queue" in plain
    assert "#1" in plain
    # the clear sequence is frame furniture; nothing else should be ANSI
    assert "\x1b[" not in plain.replace(CLEAR, "")
    ansi = render_frame(act, color=True)
    assert "\x1b[" in ansi


def test_watch_frame_flags_new_pr():
    prs = [_pr(1, number=5)]
    act = build_activity("t", prs, [], [], window_days=30)
    frame = render_frame(act, color=False, new_keys={"acme/app#5"}, tick=2)
    assert " new" in frame


def test_watch_empty_window():
    act = build_activity("t", [], [], [], window_days=30)
    frame = render_frame(act, color=False)
    assert "no pull requests in this window" in frame


def test_watch_once_command(monkeypatch, capsys):
    def fake_fetch(
        client, user, days=30, include_reviews=True, org=None, since=None, until=None
    ):
        return [_pr(1)], [], [], True

    monkeypatch.setattr(cli, "fetch_user_activity", fake_fetch)
    monkeypatch.setattr(cli, "GitHubClient", lambda **kw: object())
    rc = cli.run(["watch", "t", "--once", "--color", "never"])
    assert rc == 0
    assert "prsnoop watch | t" in capsys.readouterr().out


# ---------------------------------------------------------------- wrapped


def test_wrapped_merge_and_discussion_records():
    fast = _pr(10, number=1, title="quick")  # merged 0.5d later
    slow = _pr(40, number=2, title="slow one")
    # make the slow one genuinely slow: merged 12 days after creation
    slow.merged_at = slow.created_at + timedelta(days=12)
    chatty = _pr(20, number=3, merged=False, title="debate", comments=42)
    act = build_activity("t", [fast, slow, chatty], [], [], window_days=90)
    w = build_wrapped(act)
    assert w.fastest_pr_title == "quick"
    assert w.slowest_pr_days == 12.0
    assert w.hottest_pr_title == "debate"
    assert w.hottest_pr_comments == 42
    table = render_wrapped_table(w)
    assert "Fastest merge" in table and "Slowest merge" in table
    assert "Most discussed" in table and "42 comments" in table
    payload = w.to_dict()
    assert payload["hottest_pr_url"].endswith("/pull/3")


def test_wrapped_records_absent_without_merges():
    act = build_activity("t", [_pr(5, merged=False, comments=0)], [], [], window_days=30)
    w = build_wrapped(act)
    assert w.fastest_pr_title is None and w.slowest_pr_title is None
    table = render_wrapped_table(w)
    assert "Fastest merge" not in table
