"""SVG badge generation: embeddable contribution counters, no server needed.

Badges are plain SVG strings built by hand, so anyone can drop one into a
README without a hosting service. The look follows the shields.io flat
square convention on purpose: developers already trust that shape, and
the colors are GitHub's own merged-green / review-amber / neutral-gray.
"""

from __future__ import annotations

import base64
from xml.sax.saxutils import escape as xml_escape

from prsnoop.models import Activity
from prsnoop.org import OrgPulse

AMBER = "d29922"  # GitHub review "changes" amber
GREEN = "2ea043"  # GitHub merged green
GRAY = "656d76"  # GitHub neutral gray

FONT_ATTRS = "font-family='Verdana,Geneva,DejaVu Sans,sans-serif' font-size='11'"


def _badge(label: str, value: str, color: str) -> str:
    """One flat-square badge, shields.io style."""
    label_w = int(max(len(label) * 6.4 + 12, 8))
    value_w = int(max(len(value) * 6.8 + 12, 8))

    label = xml_escape(label)
    value = xml_escape(value)

    return (
        f"<svg xmlns='http://www.w3.org/2000/svg' "
        f"width='{label_w + value_w}' height='20' role='img' "
        f"aria-label='{label}: {value}'>"
        f"<title>{label}: {value}</title>"
        f"<rect width='{label_w}' height='20' fill='#24292e'/>"
        f"<rect x='{label_w}' width='{value_w}' height='20' fill='#{color}'/>"
        f"<g fill='#fff' text-anchor='middle' {FONT_ATTRS}>"
        f"<text x='{label_w // 2}' y='15'>{label}</text>"
        f"<text x='{label_w + value_w // 2}' y='15'>{value}</text>"
        f"</g></svg>"
    )


def render_badge_prs(activity: Activity) -> str:
    """Badge: total PRs authored in the window."""
    return _badge("prsnooped PRs", str(activity.stats.prs_authored), GRAY)


def render_badge_merged(activity: Activity) -> str:
    """Badge: merged PR count."""
    return _badge("merged PRs", str(activity.stats.prs_merged), GREEN)


def render_badge_merge_rate(activity: Activity) -> str:
    """Badge: merge rate percentage."""
    pct = f"{activity.stats.merge_rate * 100:.0f}%"
    return _badge("merge rate", pct, AMBER)


def render_badge_streak(activity: Activity) -> str:
    """Badge: longest activity streak in days."""
    return _badge("longest streak", f"{activity.stats.longest_streak_days}d", AMBER)


BADGES: dict[str, object] = {
    "prs": render_badge_prs,
    "merged": render_badge_merged,
    "rate": render_badge_merge_rate,
    "streak": render_badge_streak,
}


def render_badge(activity: Activity) -> str:
    """Badge format output: all badges as ready-to-paste Markdown data URIs."""
    lines = [
        f"<!-- Generated by prsnoop for {activity.user}. "
        f"Regenerate with: prsnoop {activity.user} --format badge -o badges.md -->"
    ]
    for name, fn in BADGES.items():
        svg = fn(activity)  # type: ignore[operator]
        data_uri = "data:image/svg+xml;base64," + base64.b64encode(
            svg.encode("utf-8")
        ).decode("ascii")
        lines.append(f"![{name}]({data_uri})")
    return "\n".join(lines) + "\n"


def render_pulse_badge(pulse: OrgPulse) -> str:
    """Badge format for org and repo pulses: ready-to-paste Markdown."""
    lines = [
        f"<!-- Generated by prsnoop for {pulse.org}. "
        f"Regenerate with: prsnoop {pulse.label} {pulse.org}"
        f" --format badge -o badges.md -->"
    ]
    rate = f"{pulse.prs_merged / pulse.prs_opened * 100:.0f}%" if pulse.prs_opened else "0%"
    entries = [
        ("prs opened", str(pulse.prs_opened), GRAY),
        ("merged", str(pulse.prs_merged), GREEN),
        ("merge rate", rate, AMBER),
        ("authors", str(pulse.authors), GRAY),
    ]
    for name, value, color in entries:
        svg = _badge(name, value, color)
        data_uri = "data:image/svg+xml;base64," + base64.b64encode(
            svg.encode("utf-8")
        ).decode("ascii")
        lines.append(f"![{name}]({data_uri})")
    return "\n".join(lines) + "\n"
