"""Battle: a head-to-head versus web page between two contributors.

One self-contained HTML file: mirrored stat panels, animated metric bars
that fill toward whoever is winning, a per-metric win tally, and a verdict
banner. The crowd-pleaser for compare demos.
"""
from __future__ import annotations

import json

from prsnoop.models import Activity, JsonDict
from prsnoop.score import compute_score


def _side(activity: Activity) -> JsonDict:
    s = activity.stats
    hs = compute_score(activity)
    return {
        "user": activity.user,
        "prs": s.prs_authored,
        "merged": s.prs_merged,
        "rate": round(s.merge_rate * 100, 1),
        "reviews": s.reviews_given,
        "issues": s.issues_opened,
        "added": s.lines_added,
        "streak": s.longest_streak_days,
        "active": s.active_days,
        "repos": s.distinct_repos,
        "langs": s.distinct_languages,
        "median": s.median_days_to_merge,
        "score": round(hs.total, 1),
        "grade": hs.grade,
    }


METRICS = [
    ("prs", "pull requests", "higher"),
    ("merged", "merged", "higher"),
    ("rate", "merge rate %", "higher"),
    ("reviews", "reviews given", "higher"),
    ("issues", "issues opened", "higher"),
    ("added", "lines added", "higher"),
    ("streak", "best streak (d)", "higher"),
    ("active", "active days", "higher"),
    ("repos", "repositories", "higher"),
    ("langs", "languages", "higher"),
    ("median", "median merge (d)", "lower"),
    ("score", "health score", "higher"),
]

_CSS = """
*{margin:0;padding:0;box-sizing:border-box}
body{background:#0a0c10;color:#e8edf4;min-height:100vh;
font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
display:flex;flex-direction:column;align-items:center;padding:40px 18px}
.vs{font-size:clamp(40px,10vw,96px);font-weight:900;letter-spacing:-3px;margin:6px 0 2px}
.vs .a{color:#58a6ff}.vs .x{color:#f4633a}
.tag{color:#8b95a5;font-size:14px;margin-bottom:26px}
.duel{display:grid;grid-template-columns:1fr 1fr;gap:22px;width:100%;max-width:900px}
@media(max-width:680px){.duel{grid-template-columns:1fr}}
.side{background:#12161d;border:1px solid #242b36;border-radius:18px;padding:22px}
.side.win{border-color:#41d67c;box-shadow:0 0 30px rgba(65,214,124,.12)}
.side h2{font-size:24px;margin-bottom:2px}
.side .g{color:#8b95a5;font-size:13px;margin-bottom:14px}
.metric{margin:11px 0}
.metric .row{display:flex;justify-content:space-between;font-size:13px;margin-bottom:5px}
.metric .row .lab{color:#8b95a5}
.metric .row b{font-variant-numeric:tabular-nums}
.metric .track{height:9px;background:#1b212b;border-radius:5px;overflow:hidden}
.metric .fill{height:100%;border-radius:5px;width:0;
transition:width 1.3s cubic-bezier(.22,1,.36,1)}
.mine .fill{background:linear-gradient(90deg,#58a6ff,#79c0ff)}
.theirs .fill{background:linear-gradient(90deg,#f4633a,#ff9d8a)}
.metric .wmark{font-size:10px;letter-spacing:1.5px;color:#41d67c}
.verdict{margin-top:28px;text-align:center}
.verdict .big{font-size:clamp(22px,5vw,38px);font-weight:800}
.verdict .score{color:#8b95a5;font-size:15px;margin-top:6px}
.tally{display:flex;gap:16px;justify-content:center;margin-top:12px;font-size:14px;color:#8b95a5}
.tally b{font-size:20px}
.tally .a{color:#58a6ff}.tally .t{color:#f4633a}
footer{margin-top:34px;color:#57616f;font-size:12px}
footer a{color:#58a6ff;text-decoration:none}
"""


def render_battle_html(a: Activity, b: Activity) -> str:
    sa, sb = _side(a), _side(b)
    payload = json.dumps({"a": sa, "b": sb, "metrics": METRICS}, ensure_ascii=True)
    metrics_js = json.dumps(METRICS)
    return (
        """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>prsnoop battle: __A__ vs __B__</title><style>__CSS__</style></head>
<body>
<div class="vs"><span class="a">__A__</span> <span style="color:#57616f">vs</span>
<span class="x">__B__</span></div>
<p class="tag">same window · same clock · every metric judged</p>
<div class="duel">
  <div class="side mine" id="sideA"><h2>__A__</h2><div class="g" id="gA"></div>
    <div id="metricsA"></div></div>
  <div class="side theirs" id="sideB"><h2>__B__</h2><div class="g" id="gB"></div>
    <div id="metricsB"></div></div>
</div>
<div class="verdict">
  <div class="big" id="verdict">judging…</div>
  <div class="score" id="vscore"></div>
  <div class="tally"><span><b class="a" id="tallyA">0</b> metrics __A__</span>
  <span><b class="t" id="tallyB">0</b> metrics __B__</span></div>
</div>
<footer>generated by <a href="https://github.com/MohammedAnasNathani/prsnoop">prsnoop battle</a>
· one file · zero assets</footer>
<script>window.__BATTLE__ = __DATA__;</script>
<script>
const B = window.__BATTLE__;
const M = __METRICS__;
const $ = (q) => document.querySelector(q);
let winsA = 0, winsB = 0;
M.forEach(([key, label, dir]) => {
  const va = B.a[key], vb = B.b[key];
  const aWins = dir === 'higher' ? va > vb : va < vb;
  const bWins = dir === 'higher' ? vb > va : vb < va;
  const peak = Math.max(va, vb, 1e-9);
  const pa = dir === 'lower' ? (1 - va / (va + vb || 1)) : va / peak;
  const pb = dir === 'lower' ? (1 - vb / (va + vb || 1)) : vb / peak;
  if (aWins) winsA++; if (bWins) winsB++;
  const row = (side, v, frac, win) => `
    <div class="metric">
      <div class="row"><span class="lab">${label}</span>
      <b>${v}${key === 'rate' ? '%' : ''} ${win ? '<span class="wmark">★ wins</span>' : ''}</b></div>
      <div class="track"><div class="fill" data-w="${Math.round(frac * 100)}"></div></div>
    </div>`;
  $('#metricsA').insertAdjacentHTML('beforeend',
    row('a', va, pa, aWins && !(va === vb)));
  $('#metricsB').insertAdjacentHTML('beforeend',
    row('b', vb, pb, bWins && !(va === vb)));
});
$('#tallyA').textContent = winsA;
$('#tallyB').textContent = winsB;
$('#gA').textContent = 'health ' + B.a.score + ' · grade ' + B.a.grade;
$('#gB').textContent = 'health ' + B.b.score + ' · grade ' + B.b.grade;
setTimeout(() => {
  document.querySelectorAll('.fill').forEach((f) => { f.style.width = f.dataset.w + '%'; });
}, 250);
setTimeout(() => {
  const total = winsA + winsB;
  let text, win = null;
  if (winsA > winsB) { win = 'A'; text = B.a.user + ' takes it'; }
  else if (winsB > winsA) { win = 'B'; text = B.b.user + ' takes it'; }
  else { text = 'dead heat'; }
  if (winsA === winsB && total > 0) {
    if (B.a.score > B.b.score) { win = 'A'; text = B.a.user + ' takes it on score'; }
    else if (B.b.score > B.a.score) { win = 'B'; text = B.b.user + ' takes it on score'; }
  }
  $('#verdict').textContent = text;
  $('#vscore').textContent = 'health score: ' + B.a.score + ' vs ' + B.b.score;
  if (win) $('#side' + win).classList.add('win');
}, 1800);
</script>
</body></html>"""
        .replace("__A__", sa["user"])
        .replace("__B__", sb["user"])
        .replace("__CSS__", _CSS)
        .replace("__DATA__", payload)
        .replace("__METRICS__", metrics_js)
    )
