"""Digest: scheduled summary formats for Slack, email, and Discord.

One snapshot in, three paste-ready formats out. Designed for cron: run
`prsnoop digest user --format slack` weekly and pipe it into a webhook.
"""
from __future__ import annotations

from dataclasses import dataclass

from prsnoop.models import Activity, JsonDict


@dataclass(slots=True)
class Digest:
    """The digest payload rendered into platform formats."""

    user: str
    window_days: int
    prs: int
    merged: int
    merge_rate: float
    reviews: int
    issues: int
    lines_added: int
    lines_deleted: int
    active_days: int
    streak: int
    momentum: str | None
    top_repo: str | None
    top_language: str | None
    headline: str

    def to_dict(self) -> JsonDict:
        return {
            "user": self.user,
            "window_days": self.window_days,
            "prs": self.prs,
            "merged": self.merged,
            "merge_rate": self.merge_rate,
            "reviews": self.reviews,
            "issues": self.issues,
            "lines_added": self.lines_added,
            "lines_deleted": self.lines_deleted,
            "active_days": self.active_days,
            "streak": self.streak,
            "momentum": self.momentum,
            "top_repo": self.top_repo,
            "top_language": self.top_language,
            "headline": self.headline,
        }


def build_digest(activity: Activity) -> Digest:
    s = activity.stats
    top_repo = s.top_repos[0][0] if s.top_repos else None
    top_lang = s.languages[0][0] if s.languages else None
    if s.prs_authored == 0:
        headline = "quiet window"
    elif s.momentum == "accelerating":
        headline = f"accelerating: {s.prs_authored} PRs and climbing"
    elif s.merge_rate >= 0.8 and s.prs_authored >= 3:
        headline = f"high impact: {s.prs_merged} merges at {s.merge_rate * 100:.0f}%"
    elif s.longest_streak_days >= 10:
        headline = f"unstoppable: {s.longest_streak_days}-day streak"
    else:
        headline = f"steady window: {s.prs_authored} PRs across {s.active_days} days"
    return Digest(
        user=activity.user,
        window_days=s.window_days,
        prs=s.prs_authored,
        merged=s.prs_merged,
        merge_rate=s.merge_rate,
        reviews=s.reviews_given,
        issues=s.issues_opened,
        lines_added=s.lines_added,
        lines_deleted=s.lines_deleted,
        active_days=s.active_days,
        streak=s.longest_streak_days,
        momentum=s.momentum,
        top_repo=top_repo,
        top_language=top_lang,
        headline=headline,
    )


def render_slack(d: Digest) -> str:
    """Slack mrkdwn block, paste-ready for an incoming webhook."""
    lines = [
        f":chart_with_upwards_trends: *prsnoop weekly digest: {d.user}*",
        f"_{d.headline}_",
        "",
        f"• PRs: *{d.prs}* opened, *{d.merged}* merged ({d.merge_rate * 100:.0f}% rate)",
        f"• Lines: *+{d.lines_added:,}* / -{d.lines_deleted:,}",
        f"• Reviews: *{d.reviews}* · Issues: *{d.issues}*",
        f"• Active days: *{d.active_days}* · Best streak: *{d.streak}d*",
    ]
    if d.top_repo:
        lines.append(f"• Busiest repo: *{d.top_repo}*")
    if d.top_language:
        lines.append(f"• Top language: *{d.top_language}*")
    if d.momentum:
        lines.append(f"• Momentum: *{d.momentum}*")
    lines += ["", "_generated by prsnoop_"]
    return "\n".join(lines)


def render_email(d: Digest) -> str:
    """Plain-text email body."""
    return "\n".join([
        f"Subject: prsnoop digest: {d.user}, last {d.window_days} days",
        "",
        f"{d.headline}",
        "",
        f"  Pull requests : {d.prs} opened, {d.merged} merged ({d.merge_rate * 100:.0f}%)",
        f"  Lines changed : +{d.lines_added:,} / -{d.lines_deleted:,}",
        f"  Reviews       : {d.reviews}",
        f"  Issues        : {d.issues}",
        f"  Active days   : {d.active_days}",
        f"  Best streak   : {d.streak} days",
        f"  Busiest repo  : {d.top_repo or '-'}",
        f"  Top language  : {d.top_language or '-'}",
        f"  Momentum      : {d.momentum or '-'}",
        "",
        "-- generated by prsnoop",
    ])


def render_discord(d: Digest) -> str:
    return "\n".join([
        "**prsnoop digest**",
        f"> {d.headline}",
        f"PRs **{d.prs}** ({d.merged} merged, {d.merge_rate * 100:.0f}%) · "
        f"+{d.lines_added:,}/-{d.lines_deleted:,}",
        f"reviews **{d.reviews}** · issues **{d.issues}** · active **{d.active_days}d** · "
        f"streak **{d.streak}d**",
    ])


def render_digest(d: Digest, fmt: str) -> str:
    if fmt == "email":
        return render_email(d)
    if fmt == "discord":
        return render_discord(d)
    return render_slack(d)
