"""Renderers: turn an Activity into human-readable output.

Each renderer is a pure function ``render(activity) -> str`` so new formats
are one function away, and output is deterministic for tests.

All output is plain ASCII by design: reports must survive every terminal,
pager, diff view, and legacy Windows console without mangling. States are
marked MERGED / OPEN / CLOSED in text, not symbols.
"""
from __future__ import annotations

import csv
import io
import json
from collections.abc import Callable
from html import escape as html_escape

from prsnoop.badge import render_badge
from prsnoop.models import MERGED, OPEN, Activity, PRRecord

Renderer = Callable[[Activity], str]

_STATE_LABEL = {MERGED: "merged", OPEN: "open", "closed": "closed"}


def _fmt_days(value: float | None) -> str:
    return "-" if value is None else f"{value:.1f}d"


def _fmt_pct(value: float) -> str:
    return f"{value * 100:.0f}%"


# --------------------------------------------------------------------- table

def render_table(activity: Activity) -> str:
    """Compact human summary for the terminal."""
    s = activity.stats
    window = s.since or f"last {s.window_days} days"
    if s.until:
        window += f" to {s.until}"
    lines = [
        f"prsnoop | {activity.user}",
        f"window: {window}",
        "",
        f"  Pull requests      {s.prs_authored}",
        f"    merged           {s.prs_merged}",
        f"    open             {s.prs_open}",
        f"    closed           {s.prs_closed_unmerged}",
        f"  Reviews given      {s.reviews_given}",
        f"  Issues opened      {s.issues_opened} (closed: {s.issues_closed})",
        f"  Lines changed      +{s.lines_added} / -{s.lines_deleted}",
        f"  Merge rate         {_fmt_pct(s.merge_rate)}",
        f"  Merge time         median {_fmt_days(s.median_days_to_merge)},"
        f" p90 {_fmt_days(s.p90_days_to_merge)}",
        f"  Active days        {s.active_days} (avg {s.avg_prs_per_active_day} PRs/day)",
        f"  Streaks            longest {s.longest_streak_days}d,"
        f" current {s.current_streak_days}d",
        f"  Repos              {s.distinct_repos}",
    ]
    if s.busiest_day:
        lines.append(
            f"  Busiest day        {s.busiest_day} ({s.busiest_day_count} items)"
        )
    if s.languages:
        mix = ", ".join(f"{lang} {n}" for lang, n in s.languages[:5])
        lines.append(f"  Languages          {mix}")

    lines += ["", "  Recent pull requests"]
    for pr in activity.prs[:10]:
        lines.append(
            f"  [{_STATE_LABEL[pr.state]:>6}] {pr.repo}#{pr.number} {pr.title[:44]}"
        )
    if not activity.prs:
        lines.append("  (none)")
    lines += ["", "  Daily activity"]
    lines += [f"    {da.date}  {'#' * min(da.total, 30)}" for da in s.day_activity[:14]]
    if len(s.day_activity) > 14:
        lines.append(f"    ... {len(s.day_activity) - 14} more days")
    if not s.day_activity:
        lines.append("    (none)")
    return "\n".join(lines)


# ------------------------------------------------------------------ markdown

def _md_pr_row(pr: PRRecord) -> str:
    label = _STATE_LABEL[pr.state]
    return (
        f"| {label} | [{pr.repo}#{pr.number}]({pr.url}) "
        f"| {pr.title} | +{pr.additions}/-{pr.deletions} "
        f"| {_fmt_days(pr.days_to_merge)} |"
    )


def render_markdown(activity: Activity) -> str:
    """GitHub-flavored Markdown report."""
    s = activity.stats
    window = s.since or f"last {s.window_days} days"
    if s.until:
        window += f" to {s.until}"
    out: list[str] = [
        f"# Contribution report: {activity.user}",
        "",
        f"_Generated by [prsnoop](https://github.com/MohammedAnasNathani/prsnoop)"
        f" on {activity.generated_at.strftime('%Y-%m-%d %H:%M UTC')} | window: {window}_",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Pull requests | {s.prs_authored} |",
        f"| Merged | {s.prs_merged} |",
        f"| Open | {s.prs_open} |",
        f"| Reviews given | {s.reviews_given} |",
        f"| Issues opened | {s.issues_opened} |",
        f"| Lines changed | +{s.lines_added} / -{s.lines_deleted} |",
        f"| Merge rate | {_fmt_pct(s.merge_rate)} |",
        f"| Median time to merge | {_fmt_days(s.median_days_to_merge)} |",
        f"| P90 time to merge | {_fmt_days(s.p90_days_to_merge)} |",
        f"| Active days | {s.active_days} |",
        f"| Longest streak | {s.longest_streak_days} days |",
        f"| Current streak | {s.current_streak_days} days |",
        f"| Distinct repos | {s.distinct_repos} |",
        "",
    ]
    if s.top_repos:
        out += ["## Top repositories", "", "| Repository | PRs |", "|---|---:|"]
        out += [f"| [{repo}](https://github.com/{repo}) | {n} |" for repo, n in s.top_repos]
        out.append("")
    if s.languages:
        out += ["## Languages", "", "| Language | PRs |", "|---|---:|"]
        out += [f"| {lang} | {n} |" for lang, n in s.languages]
        out.append("")
    if s.day_activity:
        out += [
            "## Daily activity",
            "",
            "| Date | PRs | Merged | Issues | Reviews | Total |",
            "|---|---:|---:|---:|---:|---:|",
        ]
        out += [
            f"| {da.date} | {da.prs} | {da.merged} | {da.issues}"
            f" | {da.reviews} | {da.total} |"
            for da in s.day_activity
        ]
        out.append("")
    if activity.prs:
        out += [
            "## Pull requests",
            "",
            "| State | PR | Title | Size | Days to merge |",
            "|---|---|---|---|---|",
        ]
        out += [_md_pr_row(pr) for pr in activity.prs]
        out.append("")
    if activity.reviews:
        out += [
            "## Reviews given",
            "",
            "| PR | Review | When |",
            "|---|---|---|",
        ]
        out += [
            f"| [{r.repo}#{r.pr_number}]({r.pr_url}) | {r.state} | "
            f"{r.submitted_at.strftime('%Y-%m-%d')} |"
            for r in activity.reviews
        ]
        out.append("")
    if activity.issues:
        out += [
            "## Issues opened",
            "",
            "| Issue | State | Comments |",
            "|---|---|---|",
        ]
        out += [
            f"| [{i.repo}#{i.number}]({i.url}) | {i.state} | {i.comments} |"
            for i in activity.issues
        ]
        out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------------- html

_CSS = """\
:root { color-scheme: light dark; }
body { font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; margin: 2rem auto;
       max-width: 56rem; padding: 0 1rem; line-height: 1.55; }
h1, h2 { line-height: 1.2; }
table { border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: 0.92rem; }
th, td { text-align: left; padding: 0.45rem 0.6rem; border: 1px solid #d0d7de;
         vertical-align: top; }
th { background: #f6f8fa; }
@media (prefers-color-scheme: dark) { th { background: #21262d; }
  th, td { border-color: #30363d; } }
.meta { color: #656d76; font-size: 0.9rem; }
.bars div { margin: 0.1rem 0; font-family: ui-monospace, monospace; font-size: 0.85rem; }
.state-merged { color: #1a7f37; font-weight: 600; }
.state-open { color: #9a6700; font-weight: 600; }
.state-closed { color: #656d76; }
"""


def render_html(activity: Activity) -> str:
    """Standalone HTML report, no external assets."""
    s = activity.stats

    def esc(v: object) -> str:
        return html_escape(str(v))

    cards = [
        ("Pull requests", str(s.prs_authored)),
        ("Merged", str(s.prs_merged)),
        ("Merge rate", _fmt_pct(s.merge_rate)),
        ("Reviews given", str(s.reviews_given)),
        ("Issues opened", str(s.issues_opened)),
        ("Lines", f"+{s.lines_added} / -{s.lines_deleted}"),
    ]
    summary_cells = "".join(f"<th>{esc(k)}</th>" for k, _ in cards)
    summary_vals = "".join(f"<td>{esc(v)}</td>" for _, v in cards)

    timing_rows = "".join(
        f"<tr><td>{esc(k)}</td><td>{esc(v)}</td></tr>"
        for k, v in (
            ("Median time to merge", _fmt_days(s.median_days_to_merge)),
            ("P90 time to merge", _fmt_days(s.p90_days_to_merge)),
            ("Active days", str(s.active_days)),
            ("Longest streak", f"{s.longest_streak_days} days"),
            ("Current streak", f"{s.current_streak_days} days"),
            ("Distinct repos", str(s.distinct_repos)),
        )
    )

    def pr_row(pr: PRRecord) -> str:
        label = _STATE_LABEL[pr.state]
        cls = {"merged": "state-merged", "open": "state-open"}.get(label, "state-closed")
        return (
            "<tr>"
            f'<td class="{cls}">{esc(label)}</td>'
            f'<td><a href="{esc(pr.url)}">{esc(f"{pr.repo}#{pr.number}")}</a></td>'
            f"<td>{esc(pr.title)}</td>"
            f"<td>+{pr.additions}/-{pr.deletions}</td>"
            f"<td>{esc(_fmt_days(pr.days_to_merge))}</td>"
            "</tr>"
        )

    pr_rows = "".join(pr_row(pr) for pr in activity.prs)
    review_rows = "".join(
        "<tr>"
        f'<td><a href="{esc(r.pr_url)}">{esc(f"{r.repo}#{r.pr_number}")}</a></td>'
        f"<td>{esc(r.state)}</td>"
        f"<td>{esc(r.submitted_at.strftime('%Y-%m-%d'))}</td>"
        "</tr>"
        for r in activity.reviews
    )
    issue_rows = "".join(
        "<tr>"
        f'<td><a href="{esc(i.url)}">{esc(f"{i.repo}#{i.number}")}</a></td>'
        f"<td>{esc(i.title)}</td>"
        f"<td>{esc(i.state)}</td>"
        f"<td>{i.comments}</td>"
        "</tr>"
        for i in activity.issues
    )

    day_bars = ""
    if s.day_activity:
        max_total = max(da.total for da in s.day_activity)
        rows = "".join(
            f"<div>{da.date} "
            + ("&#9612;" * (int(da.total / max_total * 26) if max_total else 0))
            + f" {da.total}</div>"
            for da in s.day_activity
        )
        day_bars = f"<h2>Daily activity</h2><div class='bars'>{rows}</div>"

    prs_html = (
        f"<h2>Pull requests</h2><table>"
        f"<tr><th>State</th><th>PR</th><th>Title</th><th>Size</th><th>Merged in</th></tr>"
        f"{pr_rows}</table>"
        if activity.prs else ""
    )
    reviews_html = (
        f"<h2>Reviews given</h2><table>"
        f"<tr><th>PR</th><th>Review</th><th>When</th></tr>{review_rows}</table>"
        if activity.reviews else ""
    )
    issues_html = (
        f"<h2>Issues opened</h2><table>"
        f"<tr><th>Issue</th><th>Title</th><th>State</th><th>Comments</th></tr>"
        f"{issue_rows}</table>"
        if activity.issues else ""
    )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>prsnoop | {esc(activity.user)}</title>
<style>{_CSS}</style>
</head>
<body>
<h1>Contribution report: {esc(activity.user)}</h1>
<p class="meta">Generated by <a href="https://github.com/MohammedAnasNathani/prsnoop">prsnoop</a>
on {activity.generated_at.strftime('%Y-%m-%d %H:%M UTC')}</p>
<table>
<tr>{summary_cells}</tr>
<tr>{summary_vals}</tr>
</table>
<table>{timing_rows}</table>
{prs_html}
{reviews_html}
{issues_html}
{day_bars}
</body>
</html>
"""


# ----------------------------------------------------------------------- csv

def render_csv(activity: Activity) -> str:
    """One CSV row per PR: spreadsheet ready."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(
        ["repo", "number", "title", "state", "created_at", "merged_at",
         "additions", "deletions", "changed_files", "labels", "comments",
         "language", "days_to_merge", "url"]
    )
    for pr in activity.prs:
        writer.writerow(
            [pr.repo, pr.number, pr.title, pr.state,
             pr.created_at.strftime("%Y-%m-%d"),
             pr.merged_at.strftime("%Y-%m-%d") if pr.merged_at else "",
             pr.additions, pr.deletions, pr.changed_files,
             ";".join(pr.labels), pr.comments, pr.language,
             f"{pr.days_to_merge:.2f}" if pr.days_to_merge is not None else "",
             pr.url]
        )
    return buf.getvalue()


# ---------------------------------------------------------------------- json

def render_json(activity: Activity) -> str:
    """Complete snapshot including derived stats."""
    return json.dumps(activity.to_dict(), indent=2, ensure_ascii=True)


RENDERERS: dict[str, Renderer] = {
    "table": render_table,
    "markdown": render_markdown,
    "html": render_html,
    "csv": render_csv,
    "json": render_json,
    "badge": render_badge,
}
